
<!doctype html>
<html>
<head>
<base href="https://www.radiothiva.gr/" />
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Κορωνοϊός: Έξι νέα κρούσματα στη Βοιωτία - Δέκα στην Εύβοια</title>
<meta name='keywords' content='ΚΟΡΩΝΟΙΟΣ ΒΟΙΩΤΙΑ ΣΤΕΡΕΑ ΕΛΛΑΔΑ ΚΡΟΥΣΜΑΤΑ' />
<meta name='description' content='Μια ακόμη ημέρα τα νέα κρούσματα του κορωνοϊού, που αφορούν την Πέμπτη 8 Οκτωβρίου, ήταν ιδιαίτερα υψηλά, τόσο στη Στερεά...' />
<meta property='og:type' content='website' />
<meta name='twitter:card' content='summary' />
<meta property='og:title' content='Κορωνοϊός: Έξι νέα κρούσματα στη Βοιωτία - Δέκα στην Εύβοια' />
<meta property='og:description' content='Μια ακόμη ημέρα τα νέα κρούσματα του κορωνοϊού, που αφορούν την Πέμπτη 8 Οκτωβρίου, ήταν ιδιαίτερα υψηλά, τόσο στη Στερεά...' /> 
<meta name='twitter:title' content='Κορωνοϊός: Έξι νέα κρούσματα στη Βοιωτία - Δέκα στην Εύβοια' />  
<meta name='twitter:description' content='Μια ακόμη ημέρα τα νέα κρούσματα του κορωνοϊού, που αφορούν την Πέμπτη 8 Οκτωβρίου, ήταν ιδιαίτερα υψηλά, τόσο στη Στερεά...' /> 
<meta itemprop='name' content='Κορωνοϊός: Έξι νέα κρούσματα στη Βοιωτία - Δέκα στην Εύβοια' />  
<meta itemprop='description'  content='Μια ακόμη ημέρα τα νέα κρούσματα του κορωνοϊού, που αφορούν την Πέμπτη 8 Οκτωβρίου, ήταν ιδιαίτερα υψηλά, τόσο στη Στερεά...' /> 
<meta property='og:url' content='https://www.radiothiva.gr/content/5782/koronoios-eksi-nea-kroysmata-sti-boiotia-deka-stin-eyboia-' /> 
<meta name='twitter:url' content='https://www.radiothiva.gr/content/5782/koronoios-eksi-nea-kroysmata-sti-boiotia-deka-stin-eyboia-' /> 
<meta property='og:image' content='https://www.radiothiva.gr/datafiles/cms5782l.jpg' /> 
<meta name='twitter:image' content='https://www.radiothiva.gr/datafiles/cms5782l.jpg' /> 
<meta itemprop='image' content='https://www.radiothiva.gr/datafiles/cms5782l.jpg' /> 


<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&amp;subset=cyrillic-ext,greek-ext" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,500,600,700&display=swap&subset=greek" rel="stylesheet">
<link href="style/style.css" rel="stylesheet" type="text/css">
<script src="scripts/jquery-3.3.1.js"></script> 

<!-- Slick Carousel -->
<link href="scripts/slick/slick.css" rel="stylesheet" type="text/css">
<script src="scripts/slick/slick.js"></script> 

<!-- Fancybox -->
<link href="scripts/fancybox/jquery.fancybox.css" rel="stylesheet" type="text/css">
<script src="Scripts/fancybox/jquery.fancybox.js"></script> 

<!----> 
<script src="Scripts/functions.js"></script> 
<script src="responsive/responsive.js"></script>

<script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5e10c6bc292f7b00127b9d37&product=inline-share-buttons&cms=sop' async='async'></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-80904940-1"></script>

<script>

  window.dataLayer = window.dataLayer || [];

  function gtag(){dataLayer.push(arguments);}

  gtag('js', new Date());

  gtag('config', 'UA-80904940-1');

</script>


<script type="text/javascript" data-cfasync="false">
var _foxpush = _foxpush || [];
_foxpush.push(['_setDomain', 'radiothivagr']);
(function(){
var foxscript = document.createElement('script');
foxscript.src = '//cdn.foxpush.net/sdk/foxpush_SDK_min.js';
foxscript.type = 'text/javascript';
foxscript.async = 'true';
var fox_s = document.getElementsByTagName('script')[0];
fox_s.parentNode.insertBefore(foxscript, fox_s);})();
</script>



<script data-ad-client="ca-pub-7541400029751701" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

</head>
<body>

<header>
	<div class="box">
		<div class="logo"><a href="/">Radio Thiva</a></div>
		<div class="rightbox">
			<div class="radio">
				<div class="live">
					<iframe width="100%" height="50"  border="0" style="border: 0; box-shadow: 0  #fff;" src="https://radiothiva.realserver.info/"></iframe>
					<!--<a href="http://realserver.info:2199/start/radiothiva/" target="_blank">Live Radio</a>--></div>
				<div class="data">
					<h3>Ακούστε Ζωντανά</h3>
					<p class='program'><a href='javascript:void(0)'>Λίστα Τραγουδιών</a></p><p class='producer'><a href='javascript:void(0)'>Ράδιο Θήβα</a></p>
					<!--<p class="program"><a href="">Ενημερωμένος Πολίτης</a></p>
					<p class="producer"><a href="">Γιώργος Πέππας</a></p>-->
				</div>
			</div>
			<div class="tv"><a href="https://www.radiothiva.gr/content/1865/web-tv-" target="_blank">TV</a></div>
			<div class="social">
				<a href="https://www.facebook.com/radiothiva/" target="_blank" class="facebook">facebook</a>
				<a href="https://twitter.com/RadioThiva" target="_blank" class="twitter">twitter</a>
				<a href="https://www.instagram.com/radio_thiva/?hl=el" target="_blank" class="instagram">instagram</a>
				<!--<a href="#" class="google">google</a>-->
				<a href="https://www.youtube.com/user/RadioThiva975" target="_blank" class="youtube">youtube</a>
				<a href="https://soundcloud.com/user-380579493" target="_blank" class="soundcloud">soundcloud</a>
			</div>
			<div class="searchbutton">
				<a href="#" class="search">Αναζήτηση</a>
				<div class="searchbox overpanel">
					<div class="box">
						<a href="#" class="close">close</a>
						<form id="searchform" name="searchform" method="get" action="search.asp">
							<p>
								<label for="searchfor">Αναζήτηση:</label>
								<input name="searchfor" type="search" id="searchfor" placeholder="Αναζήτηση για">
								<input type="submit" name="searchsubmit" id="searchsubmit" value="Αναζήτηση">
							</p>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</header><nav>
  	<div class="box">
    	<ul class="menu">
      		
					<li><a href="content.asp?id=4&title=eidiseis-" class="more">Ειδήσεις</a>
						
							<ul>
								
									<li><a href="content.asp?id=29&title=boiotia-">Βοιωτία</a></li>
								
									<li><a href="content.asp?id=30&title=sterea-ellada-">Στερεά Ελλάδα</a></li>
								
									<li><a href="content.asp?id=31&title=ellada-">Ελλάδα</a></li>
								
									<li><a href="content.asp?id=32&title=kosmos-">Κόσμος</a></li>
								
							</ul>
						
					</li>						
				
					<li><a href="content.asp?id=5&title=athlitika-" >Αθλητικά</a>
						
					</li>						
				
					<li><a href="content.asp?id=6&title=entheta-" class="more">Ένθετα</a>
						
							<ul>
								
									<li><a href="content.asp?id=1321&title=sinema-">Σινεμά</a></li>
								
									<li><a href="content.asp?id=348&title=texnologia-">Τεχνολογία</a></li>
								
									<li><a href="content.asp?id=1322&title=gaming-">Gaming</a></li>
								
									<li><a href="content.asp?id=350&title=periballon-">Περιβάλλον</a></li>
								
									<li><a href="content.asp?id=1323&title=moysiki-">Μουσική</a></li>
								
									<li><a href="content.asp?id=1411&title=psyxagogia-">Ψυχαγωγία</a></li>
								
									<li><a href="content.asp?id=3879&title=diagonismoi-">Διαγωνισμοί</a></li>
								
							</ul>
						
					</li>						
				
					<li><a href="content.asp?id=33&title=synenteykseis-" >Συνεντεύξεις</a>
						
					</li>						
				
					<li><a href="https://www.radiothiva.gr/content/2058/programma-" >Πρόγραμμα</a>
						
					</li>						
				
					<li><a href="content.asp?id=7&title=epikoinonia-" >Επικοινωνία</a>
						
					</li>						
				
    	</ul>
  		<div href="#" class="nightmode"><a href="#">Night Mode</a></div>
	</div>
</nav>

<main>
  	<div class="box clearfix">
    	<div class="path">
        	<p><a href="/">Αρχική</a><a href='content.asp?id=4&title=eidiseis-'>Ειδήσεις</a><a href='content.asp?id=30&title=sterea-ellada-'>Στερεά Ελλάδα</a><strong>Κορωνοϊός: Έξι νέα κρούσματα στη Βοιωτία - Δέκα στην Εύβοια</strong></p>
      	</div>
				
		
			
		 	<div class="content">
				<article class="mainarticle">
					<div class="topbar">
						<p class="city">ΣΤΕΡΕΑ ΕΛΛΑΔΑ</p>
						
							<p class="tags">#TAGS:
								
									<a href="search.asp?searchtag=Κορωνοϊός">Κορωνοϊός</a>&nbsp;
								
									<a href="search.asp?searchtag=Στερεά Ελλάδα">Στερεά Ελλάδα</a>&nbsp;
								
									<a href="search.asp?searchtag=Εύβοια">Εύβοια</a>&nbsp;
								
									<a href="search.asp?searchtag=Βοιωτία">Βοιωτία</a>&nbsp;
								
							</p>
						
					</div>          
					<figure class="photo"><img src='/datafiles/cms5782.jpg?width=' border='0' alt='Κορωνοϊός: Έξι νέα κρούσματα στη Βοιωτία - Δέκα στην Εύβοια' title='Κορωνοϊός: Έξι νέα κρούσματα στη Βοιωτία - Δέκα στην Εύβοια'  /></figure>				
					<div class="texts">  
						<h1 class="articletitle">Κορωνοϊός: Έξι νέα κρούσματα στη Βοιωτία - Δέκα στην Εύβοια</h1>
						
							<h2>Παραμένουν σε υψηλούς αριθμούς τα νέα κρούσματα της πανδημίας</h2>
						
						<div class="infobar">
							<p class="date">Παρασκευή, 9 Οκτωβρίου 2020</p>
							
								<p class="author">Γιώργος Πέππας</p>
							
						</div>
						<div class="buttonsbar">							
							<div class="social"><div class="sharethis-inline-share-buttons"></div></div>
						</div>    
						<div class="description textbox"><p><strong>Μ</strong>ια ακόμη ημέρα τα νέα κρούσματα του κορωνοϊού, που αφορούν την Πέμπτη 8 Οκτωβρίου, ήταν ιδιαίτερα υψηλά, τόσο στη Στερεά Ελλάδα όσο και στην Ελλάδα, προκαλώντας ιδιαίτερη ανησυχία.</p>
<p>Στη περίπτωση της Στερεάς Ελλάδας, υπήρχαν συνολικά δέκα έξι νέα κρούσματα, έξι στη Βοιωτία και δέκα στην Εύβοια. Αναλυτικότερα, ένα ζευγάρι στον Ορχομενό βρέθηκε θετικό στον κορωνοϊό, ένας 40χρονος από τον Αγ. Ανδρέα, ένας 50χρονος αλλοδαπός από τον Αγ. Θωμά, μια 47χρονη από τη Λιβαδειά καθώς και μια 26χρονη έγκυος από τη Θήβα η οποία μεταφέρθηκε στο Αττικό νοσοκομείο.</p>
<p>Στην Εύβοια από την άλλη πλευρά, υπήρξαν τέσσερα κρούσματα στη Χαλκίδα, ένας 53χρονος, ένας 23χρονος, μια 54χρονη και μια 23χρονη. Ακόμη βρέθηκε θετικός μιας 20χρονη στα Ψαχνά, μια 25χρονη από τα Λέπουρα, μια 67χρονη από τον Αγ. Νικόλαο, καθώς βρέθηκαν και δύο κρούσματα, σε μια 48χρονη, ένας 48χρονος και μια 16χρονη, που συνδέονται με προηγούμενο κρούσμα σε αλλοδαπό που νοσηλεύεται στο Γ.Ν. Χαλκίδας.</p>
<p><strong>Η Δήμαρχος Ορχομενού, κ. Καράλη, δήλωσε τα εξής αναφορικά με τα δύο κρούσματα στον Δήμο:</strong> <em>&laquo;Από εδώ και πέρα θα είναι ένα συνηθισμένο φαινόμενο και θα πρέπει να προσαρμοστούμε ανάλογα.</em></p>
<p><em>Δυο κρούσματα κορονοιου σήμερα στον Ορχομενό.</em></p>
<p><em>Γίνεται ιχνηλάτηση</em></p>
<p><em>Ακολουθούνται όλες οι διαδικασίες που προβλέπει ο Νόμος από τον ΕΟΔΥ και την Περιφέρεια.</em></p>
<p><em>Είμαστε όλοι εδώ και προσέχουμε!!!</em></p>
<p><em>Σε αυτή την ισχυρή σχέση αλληλεξάρτησης είμαστε όλοι μαζί.!!!</em></p>
<p><em>Προστατεύουμε και προστατευόμαστε.</em></p>
<p><em>Με σεβασμό στον συνάνθρωπο ,στον γείτονα, τον φίλο, τον σύντροφό, την οικογένεια</em></p>
<p><em>Με σεβασμό στην ζωή!!!</em></p>
<p><em>Με ψυχραιμία και δύναμη&raquo;</em></p>
<p><strong>Η γεωγραφική κατανομή των κρουσμάτων</strong></p>
<p>- 17 κρούσματα κατά τους ελέγχους που διενεργήθηκαν στις πύλες εισόδου της χώρας<br />
<br />
- 2 εισαγόμενα κρούσματα που προσήλθαν αυτοβούλως για έλεγχο<br />
<br />
- 219 κρούσματα στην Περιφέρεια Αττικής , εκ των οποίων 31 συνδέονται με γνωστές συρροές, ενώ 8 αναφέρουν πρόσφατο ταξίδι στο εσωτερικό της χώρας<br />
<br />
- 33 κρούσματα στην Π.Ε. Θεσσαλονίκης, εκ των οποίων 1 συνδέεται με γνωστή συρροή<br />
<br />
- 4 κρούσματα στην Π.Ε. Αιτωλοακαρνανίας<br />
<br />
- 9 κρούσματα στην Π.Ε. Αχαΐας, εκ των οποίων 1 συνδέεται με γνωστή συρροή<br />
<br />
- 6 κρούσματα από Π.Ε. Βοιωτίας<br />
<br />
- 3 κρούσματα στην Π.Ε. Γρεβενών, εκ των οποίων 1 συνδέεται με γνωστή συρροή<br />
<br />
- 2 κρούσματα στην Π.Ε. Δράμας, εκ των οποίων 1 συνδέεται με γνωστή συρροή<br />
<br />
- 1 κρούσμα στην Π.Ε. Έβρου<br />
<br />
- 10 κρούσματα στην Π.Ε. Εύβοιας, εκ των οποίων 5 συνδέονται με γνωστές συρροές<br />
<br />
- 3 κρούσματα στην Π.Ε. Ηλείας<br />
<br />
- 1 κρούσμα στην &nbsp;Π.Ε. Ημαθίας<br />
<br />
- 4 κρούσματα στην Π.Ε. Ηρακλείου<br />
<br />
- 20 κρούσματα από Π.Ε. Ιωαννίνων<br />
<br />
- 5 κρούσματα στην Π.Ε. Καστοριάς<br />
<br />
- 1 κρούσμα στην Π.Ε. Κέρκυρας<br />
<br />
- 10 κρούσματα στην &nbsp;Π.Ε. Κιλκίς, συνδεόμενα με γνωστή συρροή<br />
<br />
- 18 κρούσματα από Π.Ε. Κοζάνης, εκ των οποίων 3 συνδέονται με γνωστές συρροές<br />
<br />
- 8 κρούσματα από Π.Ε. Κορινθίας, εκ των οποίων 3 συνδέονται με γνωστές συρροές<br />
<br />
- 7 κρούσματα στην &nbsp;Π.Ε. Λάρισας, εκ των οποίων 4 συνδέονται με γνωστή συρροή<br />
<br />
- 2 κρούσματα στην Π.Ε. Λέσβου, εκ των οποίων 1 συνδέεται με γνωστή συρροή<br />
<br />
- 4 κρούσματα από Π.Ε. Μαγνησίας, εκ των οποίων 3 συνδέονται με γνωστή συρροή<br />
<br />
- 1 κρούσμα στην Π.Ε. Ξάνθης<br />
<br />
- 10 κρούσματα στην Π.Ε. Πέλλας<br />
<br />
- 1 κρούσμα στην Π.Ε. Πιερίας<br />
<br />
- 2 κρούσματα στην Π.Ε. Ρεθύμνου<br />
<br />
- 2 κρούσματα στην Π.Ε. Ροδόπης<br />
<br />
- 1 κρούσμα στην Π.Ε. Ρόδου<br />
<br />
- 1 κρούσμα στην Π.Ε. Σερρών<br />
<br />
- 1 κρούσμα στην Π.Ε. Σποράδων<br />
<br />
- 4 κρούσματα στην Π.Ε. Τρικάλων, εκ των οποίων 1 συνδέεται με γνωστή συρροή<br />
<br />
- 1 κρούσμα στην Π.Ε. Φλώρινας<br />
<br />
- 1 κρούσμα στην Π.Ε. Χανίων<br />
<br />
- 1 κρούσμα στην Π.Ε. Χίου<br />
<br />
- 21 κρούσματα βρίσκονται υπό διερεύνηση.</p>
<p><strong>Η ανακοίνωση του ΕΟΔΥ</strong></p>
<p><em>&laquo;Σήμερα ανακοινώνουμε 436 νέα κρούσματα του νέου ιού στη χώρα, εκ των οποίων 65 συνδέονται με γνωστές συρροές και 17 εντοπίστηκαν κατόπιν ελέγχων στις πύλες εισόδου της χώρας. Ο συνολικός αριθμός των κρουσμάτων είναι 21381, εκ των οποίων το 55.8% άνδρες.</em></p>
<p><em>3170 (14.8%) θεωρούνται σχετιζόμενα με ταξίδι από το εξωτερικό και 8727 (40.8%) είναι σχετιζόμενα με ήδη γνωστό κρούσμα.</em></p>
<p><em>91 συμπολίτες μας νοσηλεύονται διασωληνωμένοι. Η διάμεση ηλικία τους είναι 68 ετών. 25 (27.5%) είναι γυναίκες και οι υπόλοιποι άνδρες. To 90.1%, των διασωληνωμένων, έχει υποκείμενο νόσημα ή είναι ηλικιωμένοι 70 ετών και άνω. 236 ασθενείς έχουν εξέλθει από τις ΜΕΘ.</em></p>
<p><em>Τέλος, έχουμε 6 ακόμα καταγεγραμμένους θανάτους και 430 θανάτους συνολικά στη χώρα. 160 (37.2%) γυναίκες και οι υπόλοιποι άνδρες. Η διάμεση ηλικία των θανόντων συμπολιτών μας ήταν τα 78 έτη και το 96.5% είχε κάποιο υποκείμενο νόσημα ή/και ηλικία 70 ετών και άνω.&raquo;</em></p></div>
					</div>
					
					
						<section class="morearticles articleslist">
							<h1>`Αλλα άρθρα του/της&nbsp;Γιώργος Πέππας</h1>
							<div class="content">
								
<article>
	<div class="photo">
		<a href="content.asp?id=5871&title=syllalitirio-sti-thiba-gia-to-g.n.-thibas-zitoyn-amesi-stelexosi-" title="Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση"><img src='/datafiles/cms5871.jpg?width=305' border='0' alt='Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση' title='Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση'  /></a>
		<div class="city">ΘΗΒΑ</div>
		
			<div class="category videos">videos</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5871&title=syllalitirio-sti-thiba-gia-to-g.n.-thibas-zitoyn-amesi-stelexosi-" title="Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση">Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση</a></h3>
		<div class="description textbox">
			<p>Πραγματοποιήθηκε εχθές το απόγευμα, με μεγάλη συμμετοχή του κόσμου και με την τήρηση όλων των υγειονομικών πρωτοκόλλων...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5871&title=syllalitirio-sti-thiba-gia-to-g.n.-thibas-zitoyn-amesi-stelexosi-" title="Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
<article>
	<div class="photo">
		<a href="content.asp?id=5870&title=protasi-dimioyrgias-grafeioy-ilektronikis-diakybernisis-ston-dimo-thibaion-" title="Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων"><img src='/datafiles/cms5870.jpg?width=305' border='0' alt='Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων' title='Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων'  /></a>
		<div class="city">ΘΗΒΑ</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5870&title=protasi-dimioyrgias-grafeioy-ilektronikis-diakybernisis-ston-dimo-thibaion-" title="Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων">Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων</a></h3>
		<div class="description textbox">
			<p>Την Δευτέρα 12 Οκτωβρίου 2020 κατά την διάρκεια συζήτησης στην επιτροπή Οργάνωσης και Ηλεκτρονικής Διακυβέρνησης της ΠΕΔ...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5870&title=protasi-dimioyrgias-grafeioy-ilektronikis-diakybernisis-ston-dimo-thibaion-" title="Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
<article>
	<div class="photo">
		<a href="content.asp?id=5868&title=koronoios-28-parabaseis-ton-metron-sti-sterea-ellada-" title="Κορωνοϊός: 28 παραβάσεις των μέτρων στη Στερεά Ελλάδα"><img src='/datafiles/cms5868.jpg?width=305' border='0' alt='Κορωνοϊός: 28 παραβάσεις των μέτρων στη Στερεά Ελλάδα' title='Κορωνοϊός: 28 παραβάσεις των μέτρων στη Στερεά Ελλάδα'  /></a>
		<div class="city">ΣΤΕΡΕΑ ΕΛΛΑΔΑ</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5868&title=koronoios-28-parabaseis-ton-metron-sti-sterea-ellada-" title="Κορωνοϊός: 28 παραβάσεις των μέτρων στη Στερεά Ελλάδα">Κορωνοϊός: 28 παραβάσεις των μέτρων στη Στερεά Ελλάδα</a></h3>
		<div class="description textbox">
			<p>Για ακόμη μια ημέρα πραγματοποιήθηκαν εντατικοί έλεγχοι από την Αστυνομία, τόσο στη Στερεά Ελλάδα όσο και στην υπόλοιπη επικράτεια της χώρας...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5868&title=koronoios-28-parabaseis-ton-metron-sti-sterea-ellada-" title="Κορωνοϊός: 28 παραβάσεις των μέτρων στη Στερεά Ελλάδα">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
<article>
	<div class="photo">
		<a href="content.asp?id=5867&title=sta-roz-to-palaio-dimarxeio-thibas-«mazi-sti-maxi-kata-toy-karkinoy-toy-mastoy»-" title="Στα ροζ το παλαιό Δημαρχείο Θήβας - «Μαζί στη μάχη κατά του καρκίνου του μαστού»"><img src='/datafiles/cms5867.jpg?width=305' border='0' alt='Στα ροζ το παλαιό Δημαρχείο Θήβας - «Μαζί στη μάχη κατά του καρκίνου του μαστού»' title='Στα ροζ το παλαιό Δημαρχείο Θήβας - «Μαζί στη μάχη κατά του καρκίνου του μαστού»'  /></a>
		<div class="city">ΘΗΒΑ</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5867&title=sta-roz-to-palaio-dimarxeio-thibas-«mazi-sti-maxi-kata-toy-karkinoy-toy-mastoy»-" title="Στα ροζ το παλαιό Δημαρχείο Θήβας - «Μαζί στη μάχη κατά του καρκίνου του μαστού»">Στα ροζ το παλαιό Δημαρχείο Θήβας - «Μαζί στη μάχη κατά του καρκίνου του μαστού»</a></h3>
		<div class="description textbox">
			<p>Ο Δήμος Θηβαίων, για 2η συνεχόμενη χρονιά, «ντύνει» στα ροζ το παλαιό Δημαρχείο Θήβας, στα πλαίσια της παγκόσμιας...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5867&title=sta-roz-to-palaio-dimarxeio-thibas-«mazi-sti-maxi-kata-toy-karkinoy-toy-mastoy»-" title="Στα ροζ το παλαιό Δημαρχείο Θήβας - «Μαζί στη μάχη κατά του καρκίνου του μαστού»">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
<article>
	<div class="photo">
		<a href="content.asp?id=5866&title=19xronos-foititis-sti-lamia-brethike-thetikos-ston-koronoio-" title="19χρονος φοιτητής στη Λαμία βρέθηκε θετικός στον κορωνοϊό"><img src='/datafiles/cms5866.jpg?width=305' border='0' alt='19χρονος φοιτητής στη Λαμία βρέθηκε θετικός στον κορωνοϊό' title='19χρονος φοιτητής στη Λαμία βρέθηκε θετικός στον κορωνοϊό'  /></a>
		<div class="city">ΛΑΜΙΑ</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5866&title=19xronos-foititis-sti-lamia-brethike-thetikos-ston-koronoio-" title="19χρονος φοιτητής στη Λαμία βρέθηκε θετικός στον κορωνοϊό">19χρονος φοιτητής στη Λαμία βρέθηκε θετικός στον κορωνοϊό</a></h3>
		<div class="description textbox">
			<p>Ένα ακόμη κρούσμα της πανδημίας εντοπίστηκε στη Λαμία, όταν τα ξημερώματα της Τετάρτης 14 Οκτωβρίου 2020 ένας 19χρονος...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5866&title=19xronos-foititis-sti-lamia-brethike-thetikos-ston-koronoio-" title="19χρονος φοιτητής στη Λαμία βρέθηκε θετικός στον κορωνοϊό">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
<article>
	<div class="photo">
		<a href="content.asp?id=5865&title=d.-lebadeon-anoikse-platforma-gia-xorigisi-boithimatos-se-oikogeneies-oreinon-kai-meionektikon-perioxon-" title="Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών"><img src='/datafiles/cms5865.jpg?width=305' border='0' alt='Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών' title='Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών'  /></a>
		<div class="city">ΛΙΒΑΔΕΙΑ</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5865&title=d.-lebadeon-anoikse-platforma-gia-xorigisi-boithimatos-se-oikogeneies-oreinon-kai-meionektikon-perioxon-" title="Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών">Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών</a></h3>
		<div class="description textbox">
			<p>Σε ανακοίνωση που εξέδωσε ο Δήμος Λεβαδέων γνωστοποιεί πως έχει ανοίξει και λειτουργεί η ψηφιακή πλατφόρμα αιτήσεων για τη χορήγηση...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5865&title=d.-lebadeon-anoikse-platforma-gia-xorigisi-boithimatos-se-oikogeneies-oreinon-kai-meionektikon-perioxon-" title="Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
<article>
	<div class="photo">
		<a href="content.asp?id=5864&title=giota-poyloy-ektheti-i-ekpaideytiki-koinotita-tis-boiotias-apenanti-stin-pandimia-" title="Γιώτα Πούλου: Έκθετη η εκπαιδευτική κοινότητα της Βοιωτίας απέναντι στην πανδημία"><img src='/datafiles/cms5864.jpg?width=305' border='0' alt='Γιώτα Πούλου: Έκθετη η εκπαιδευτική κοινότητα της Βοιωτίας απέναντι στην πανδημία' title='Γιώτα Πούλου: Έκθετη η εκπαιδευτική κοινότητα της Βοιωτίας απέναντι στην πανδημία'  /></a>
		<div class="city">ΒΟΙΩΤΙΑ</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5864&title=giota-poyloy-ektheti-i-ekpaideytiki-koinotita-tis-boiotias-apenanti-stin-pandimia-" title="Γιώτα Πούλου: Έκθετη η εκπαιδευτική κοινότητα της Βοιωτίας απέναντι στην πανδημία">Γιώτα Πούλου: Έκθετη η εκπαιδευτική κοινότητα της Βοιωτίας απέναντι στην πανδημία</a></h3>
		<div class="description textbox">
			<p>Η Βουλευτής Βοιωτίας του ΣΥΡΙΖΑ, κ. Γιώτα Πούλου, κατέθεσε ερώτηση στη Βουλή, την οποία συνυπογράφουν 25 Βουλευτές του ΣΥΡΙΖΑ...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5864&title=giota-poyloy-ektheti-i-ekpaideytiki-koinotita-tis-boiotias-apenanti-stin-pandimia-" title="Γιώτα Πούλου: Έκθετη η εκπαιδευτική κοινότητα της Βοιωτίας απέναντι στην πανδημία">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
<article>
	<div class="photo">
		<a href="content.asp?id=5862&title=syntirisi-toy-ethnikoy-kai-eparxiakoy-diktyoy-tis-p.e.-eyrytanias-" title="Συντήρηση του εθνικού και επαρχιακού δικτύου της Π.Ε. Ευρυτανίας"><img src='/datafiles/cms5862.jpg?width=305' border='0' alt='Συντήρηση του εθνικού και επαρχιακού δικτύου της Π.Ε. Ευρυτανίας' title='Συντήρηση του εθνικού και επαρχιακού δικτύου της Π.Ε. Ευρυτανίας'  /></a>
		<div class="city">ΕΥΤΥΡΑΝΙΑ</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5862&title=syntirisi-toy-ethnikoy-kai-eparxiakoy-diktyoy-tis-p.e.-eyrytanias-" title="Συντήρηση του εθνικού και επαρχιακού δικτύου της Π.Ε. Ευρυτανίας">Συντήρηση του εθνικού και επαρχιακού δικτύου της Π.Ε. Ευρυτανίας</a></h3>
		<div class="description textbox">
			<p>Συνεχίζεται η συντήρηση του εθνικού αλλά και του επαρχιακού δικτύου της Περιφέρεια Στερεάς Ελλάδας, με την Περιφερειακή Ενότητα Ευρυτανίας να βρίσκεται...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5862&title=syntirisi-toy-ethnikoy-kai-eparxiakoy-diktyoy-tis-p.e.-eyrytanias-" title="Συντήρηση του εθνικού και επαρχιακού δικτύου της Π.Ε. Ευρυτανίας">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
<article>
	<div class="photo">
		<a href="content.asp?id=5861&title=syntakseis-noembrioy-pote-plironontai-oi-dikaioyxoi-oi-imerominies-gia-ola-ta-tameia-" title="Συντάξεις Νοεμβρίου: Πότε πληρώνονται οι δικαιούχοι - Οι ημερομηνίες για όλα τα Tαμεία"><img src='/datafiles/cms5861.jpg?width=305' border='0' alt='Συντάξεις Νοεμβρίου: Πότε πληρώνονται οι δικαιούχοι - Οι ημερομηνίες για όλα τα Tαμεία' title='Συντάξεις Νοεμβρίου: Πότε πληρώνονται οι δικαιούχοι - Οι ημερομηνίες για όλα τα Tαμεία'  /></a>
		<div class="city">ΕΛΛΑΔΑ</div>
		
	</div>
	<div class="texts">
		<h3><a href="content.asp?id=5861&title=syntakseis-noembrioy-pote-plironontai-oi-dikaioyxoi-oi-imerominies-gia-ola-ta-tameia-" title="Συντάξεις Νοεμβρίου: Πότε πληρώνονται οι δικαιούχοι - Οι ημερομηνίες για όλα τα Tαμεία">Συντάξεις Νοεμβρίου: Πότε πληρώνονται οι δικαιούχοι - Οι ημερομηνίες για όλα τα Tαμεία</a></h3>
		<div class="description textbox">
			<p>Tην Παρασκευή, 23 Οκτωβρίου, ή τη Δευτέρα στις 26 του μήνα θα ξεκινήσουν να καταβάλλονται οι συντάξεις Νοεμβρίου 2020 στους δικαιούχους...</p>
		</div>
		
			<div class="date"><a href="content.asp?id=5861&title=syntakseis-noembrioy-pote-plironontai-oi-dikaioyxoi-oi-imerominies-gia-ola-ta-tameia-" title="Συντάξεις Νοεμβρίου: Πότε πληρώνονται οι δικαιούχοι - Οι ημερομηνίες για όλα τα Tαμεία">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
	</div>
</article>
							</div>
						</section>
					
					
				</article>
			</div>
			
			<aside class="sidebar">
				<section class="popular">
					<h2>ΔΗΜΟΦΙΛΗ</h2>
<div class="tabs">
	<ul class="titles">
		<li><a href="#tab1" class="active">ΗΜΕΡΑΣ</a></li>
		<li><a href="#tab2">ΜΗΝΑ</a></li>
	</ul>
	<div class="content" id="tab1">
		<article>
	<div class="photo"><a href="content.asp?id=5856&title=koronoios-nea-kroysmata-se-libadeia,-thiba-kai-xalkida-" title="Κορωνοϊός: Νέα κρούσματα σε Λιβαδειά, Θήβα και Χαλκίδα"><img src='/datafiles/cms5856.jpg?width=305' border='0' alt='Κορωνοϊός: Νέα κρούσματα σε Λιβαδειά, Θήβα και Χαλκίδα' title='Κορωνοϊός: Νέα κρούσματα σε Λιβαδειά, Θήβα και Χαλκίδα'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5856&title=koronoios-nea-kroysmata-se-libadeia,-thiba-kai-xalkida-" title="Κορωνοϊός: Νέα κρούσματα σε Λιβαδειά, Θήβα και Χαλκίδα">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5856&title=koronoios-nea-kroysmata-se-libadeia,-thiba-kai-xalkida-" title="Κορωνοϊός: Νέα κρούσματα σε Λιβαδειά, Θήβα και Χαλκίδα">Κορωνοϊός: Νέα κρούσματα σε Λιβαδειά, Θήβα και Χαλκίδα</a></h3>
	</div>
</article><article>
	<div class="photo"><a href="content.asp?id=5865&title=d.-lebadeon-anoikse-platforma-gia-xorigisi-boithimatos-se-oikogeneies-oreinon-kai-meionektikon-perioxon-" title="Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών"><img src='/datafiles/cms5865.jpg?width=305' border='0' alt='Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών' title='Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5865&title=d.-lebadeon-anoikse-platforma-gia-xorigisi-boithimatos-se-oikogeneies-oreinon-kai-meionektikon-perioxon-" title="Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5865&title=d.-lebadeon-anoikse-platforma-gia-xorigisi-boithimatos-se-oikogeneies-oreinon-kai-meionektikon-perioxon-" title="Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών">Δ. Λεβαδέων: Ανοιξε πλατφόρμα για χορήγηση βοηθήματος σε οικογένειες ορεινών και μειονεκτικών περιοχών</a></h3>
	</div>
</article><article>
	<div class="photo"><a href="content.asp?id=5871&title=syllalitirio-sti-thiba-gia-to-g.n.-thibas-zitoyn-amesi-stelexosi-" title="Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση"><img src='/datafiles/cms5871.jpg?width=305' border='0' alt='Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση' title='Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5871&title=syllalitirio-sti-thiba-gia-to-g.n.-thibas-zitoyn-amesi-stelexosi-" title="Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5871&title=syllalitirio-sti-thiba-gia-to-g.n.-thibas-zitoyn-amesi-stelexosi-" title="Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση">Συλλαλητήριο στη Θήβα για το Γ.Ν. Θήβας - Ζητούν άμεση στελέχωση</a></h3>
	</div>
</article><article>
	<div class="photo"><a href="content.asp?id=5858&title=giorgos-moylkiotis-«se-apognosi-oi-syntaksioyxoi-agrotes»-" title="Γιώργος Μουλκιώτης: «Σε απόγνωση οι συνταξιούχοι αγρότες»"><img src='/datafiles/cms5858.jpg?width=305' border='0' alt='Γιώργος Μουλκιώτης: «Σε απόγνωση οι συνταξιούχοι αγρότες»' title='Γιώργος Μουλκιώτης: «Σε απόγνωση οι συνταξιούχοι αγρότες»'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5858&title=giorgos-moylkiotis-«se-apognosi-oi-syntaksioyxoi-agrotes»-" title="Γιώργος Μουλκιώτης: «Σε απόγνωση οι συνταξιούχοι αγρότες»">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5858&title=giorgos-moylkiotis-«se-apognosi-oi-syntaksioyxoi-agrotes»-" title="Γιώργος Μουλκιώτης: «Σε απόγνωση οι συνταξιούχοι αγρότες»">Γιώργος Μουλκιώτης: «Σε απόγνωση οι συνταξιούχοι αγρότες»</a></h3>
	</div>
</article><article>
	<div class="photo"><a href="content.asp?id=5870&title=protasi-dimioyrgias-grafeioy-ilektronikis-diakybernisis-ston-dimo-thibaion-" title="Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων"><img src='/datafiles/cms5870.jpg?width=305' border='0' alt='Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων' title='Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5870&title=protasi-dimioyrgias-grafeioy-ilektronikis-diakybernisis-ston-dimo-thibaion-" title="Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων">Τετάρτη, 14 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5870&title=protasi-dimioyrgias-grafeioy-ilektronikis-diakybernisis-ston-dimo-thibaion-" title="Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων">Πρόταση δημιουργίας Γραφείου Ηλεκτρονικής Διακυβέρνησης στον Δήμο Θηβαίων</a></h3>
	</div>
</article>
		<!--<a href="#" class="more">Δείτε όλα τα νέα</a>-->
	</div>
	<div class="content" id="tab2">
		<article>
	<div class="photo"><a href="content.asp?id=5819&title=koronoios-kroysmata-se-libadeia,-aliarto-kai-sximatari-" title="Κορωνοϊός: Κρούσματα σε Λιβαδειά, Αλίαρτο και Σχηματάρι"><img src='/datafiles/cms5819.jpg?width=305' border='0' alt='Κορωνοϊός: Κρούσματα σε Λιβαδειά, Αλίαρτο και Σχηματάρι' title='Κορωνοϊός: Κρούσματα σε Λιβαδειά, Αλίαρτο και Σχηματάρι'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5819&title=koronoios-kroysmata-se-libadeia,-aliarto-kai-sximatari-" title="Κορωνοϊός: Κρούσματα σε Λιβαδειά, Αλίαρτο και Σχηματάρι">Δευτέρα, 12 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5819&title=koronoios-kroysmata-se-libadeia,-aliarto-kai-sximatari-" title="Κορωνοϊός: Κρούσματα σε Λιβαδειά, Αλίαρτο και Σχηματάρι">Κορωνοϊός: Κρούσματα σε Λιβαδειά, Αλίαρτο και Σχηματάρι</a></h3>
	</div>
</article><article>
	<div class="photo"><a href="content.asp?id=5840&title=koronoios-pente-kroysmata-sti-libadeia-kleinoyn-sxolika-tmimata-" title="Κορωνοϊός: Πέντε κρούσματα στη Λιβαδειά - Κλείνουν σχολικά τμήματα"><img src='/datafiles/cms5840.jpg?width=305' border='0' alt='Κορωνοϊός: Πέντε κρούσματα στη Λιβαδειά - Κλείνουν σχολικά τμήματα' title='Κορωνοϊός: Πέντε κρούσματα στη Λιβαδειά - Κλείνουν σχολικά τμήματα'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5840&title=koronoios-pente-kroysmata-sti-libadeia-kleinoyn-sxolika-tmimata-" title="Κορωνοϊός: Πέντε κρούσματα στη Λιβαδειά - Κλείνουν σχολικά τμήματα">Τρίτη, 13 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5840&title=koronoios-pente-kroysmata-sti-libadeia-kleinoyn-sxolika-tmimata-" title="Κορωνοϊός: Πέντε κρούσματα στη Λιβαδειά - Κλείνουν σχολικά τμήματα">Κορωνοϊός: Πέντε κρούσματα στη Λιβαδειά - Κλείνουν σχολικά τμήματα</a></h3>
	</div>
</article><article>
	<div class="photo"><a href="content.asp?id=5811&title=a.o.-ypatoy-a.o.-neas-artakis-2-0-" title="Α.Ο. Υπάτου - Α.Ο. Νέας Αρτάκης 2-0"><img src='/datafiles/cms5811.jpg?width=305' border='0' alt='Α.Ο. Υπάτου - Α.Ο. Νέας Αρτάκης 2-0' title='Α.Ο. Υπάτου - Α.Ο. Νέας Αρτάκης 2-0'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5811&title=a.o.-ypatoy-a.o.-neas-artakis-2-0-" title="Α.Ο. Υπάτου - Α.Ο. Νέας Αρτάκης 2-0">Κυριακή, 11 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5811&title=a.o.-ypatoy-a.o.-neas-artakis-2-0-" title="Α.Ο. Υπάτου - Α.Ο. Νέας Αρτάκης 2-0">Α.Ο. Υπάτου - Α.Ο. Νέας Αρτάκης 2-0</a></h3>
	</div>
</article><article>
	<div class="photo"><a href="content.asp?id=5715&title=troxaio-ston-kombo-toy-nosokomeioy-thibas-mixanaki-paresyre-ilikiomeno-pezo-" title="Τροχαίο στον κόμβο του Νοσοκομείου Θήβας - Μηχανάκι παρέσυρε ηλικιωμένο πεζό"><img src='/datafiles/cms5715.jpg?width=305' border='0' alt='Τροχαίο στον κόμβο του Νοσοκομείου Θήβας - Μηχανάκι παρέσυρε ηλικιωμένο πεζό' title='Τροχαίο στον κόμβο του Νοσοκομείου Θήβας - Μηχανάκι παρέσυρε ηλικιωμένο πεζό'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5715&title=troxaio-ston-kombo-toy-nosokomeioy-thibas-mixanaki-paresyre-ilikiomeno-pezo-" title="Τροχαίο στον κόμβο του Νοσοκομείου Θήβας - Μηχανάκι παρέσυρε ηλικιωμένο πεζό">Δευτέρα, 5 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5715&title=troxaio-ston-kombo-toy-nosokomeioy-thibas-mixanaki-paresyre-ilikiomeno-pezo-" title="Τροχαίο στον κόμβο του Νοσοκομείου Θήβας - Μηχανάκι παρέσυρε ηλικιωμένο πεζό">Τροχαίο στον κόμβο του Νοσοκομείου Θήβας - Μηχανάκι παρέσυρε ηλικιωμένο πεζό</a></h3>
	</div>
</article><article>
	<div class="photo"><a href="content.asp?id=5774&title=koronoios-thetiki-egkyos-40-ebdomadon-apo-ti-boiotia-" title="Κορωνοϊός: Θετική έγκυος 40 εβδομάδων από τη Βοιωτία"><img src='/datafiles/cms5774.jpg?width=305' border='0' alt='Κορωνοϊός: Θετική έγκυος 40 εβδομάδων από τη Βοιωτία' title='Κορωνοϊός: Θετική έγκυος 40 εβδομάδων από τη Βοιωτία'  /></a></div>
	<div class="texts">
		
			<div class="date"><a href="content.asp?id=5774&title=koronoios-thetiki-egkyos-40-ebdomadon-apo-ti-boiotia-" title="Κορωνοϊός: Θετική έγκυος 40 εβδομάδων από τη Βοιωτία">Πέμπτη, 8 Οκτωβρίου 2020</a></div>
		
		<h3><a href="content.asp?id=5774&title=koronoios-thetiki-egkyos-40-ebdomadon-apo-ti-boiotia-" title="Κορωνοϊός: Θετική έγκυος 40 εβδομάδων από τη Βοιωτία">Κορωνοϊός: Θετική έγκυος 40 εβδομάδων από τη Βοιωτία</a></h3>
	</div>
</article>
		<!--<a href="#" class="more">Δείτε όλα τα νέα</a>-->
	</div>
</div>
				</section>
				
				<section class="producers">
					<h2>ΡΑΔΙΟΦΩΝΙΚΟΙ ΠΑΡΑΓΩΓΟΙ</h2>
<ul>
	
			<li>
				<div class="photo"><a href="content.asp?id=1867&title=giorgos-peppas-" title="Γιώργος Πέππας"><img src='/datafiles/cms1867.jpg?width=79' border='0' alt='Γιώργος Πέππας' title='Γιώργος Πέππας'  /></a></div>
				<div class="texts">
					<h3><a href="content.asp?id=1867&title=giorgos-peppas-" title="Γιώργος Πέππας">Γιώργος Πέππας</a></h3>
					
					<p class="social">
						
							<a href="https://www.facebook.com/profile.php?id=100009890326880" target="_blank" class="facebook">facebook</a>
						
					</p>
				</div>
			</li>
		
			<li>
				<div class="photo"><a href="content.asp?id=2062&title=spyros-peppas-" title="Σπύρος Πέππας"><img src='/datafiles/cms2062.jpg?width=79' border='0' alt='Σπύρος Πέππας' title='Σπύρος Πέππας'  /></a></div>
				<div class="texts">
					<h3><a href="content.asp?id=2062&title=spyros-peppas-" title="Σπύρος Πέππας">Σπύρος Πέππας</a></h3>
					
					<p class="social">
						
							<a href="https://www.facebook.com/Spercules" target="_blank" class="facebook">facebook</a>
						
							<a href="https://www.instagram.com/peppas.spy/" target="_blank" class="instagram">instagram</a>
						
					</p>
				</div>
			</li>
		
			<li>
				<div class="photo"><a href="content.asp?id=68&title=pantelis-kakas-" title="Παντελής Κάκας"><img src='/datafiles/cms68.jpg?width=79' border='0' alt='Παντελής Κάκας' title='Παντελής Κάκας'  /></a></div>
				<div class="texts">
					<h3><a href="content.asp?id=68&title=pantelis-kakas-" title="Παντελής Κάκας">Παντελής Κάκας</a></h3>
					
					<p class="social">
						
							<a href="https://www.facebook.com/pantelhs.kakas.1" target="_blank" class="facebook">facebook</a>
						
					</p>
				</div>
			</li>
		
			<li>
				<div class="photo"><a href="content.asp?id=2063&title=baggelis-makris-" title="Βαγγέλης Μακρής"><img src='/datafiles/cms2063.jpg?width=79' border='0' alt='Βαγγέλης Μακρής' title='Βαγγέλης Μακρής'  /></a></div>
				<div class="texts">
					<h3><a href="content.asp?id=2063&title=baggelis-makris-" title="Βαγγέλης Μακρής">Βαγγέλης Μακρής</a></h3>
					
					<p class="social">
						
							<a href="https://www.facebook.com/vagelis.makris.14" target="_blank" class="facebook">facebook</a>
						
					</p>
				</div>
			</li>
		
			<li>
				<div class="photo"><a href="content.asp?id=2060&title=minas-papathomas-" title="Μηνάς Παπαθωμάς"><img src='/datafiles/cms2060.jpg?width=79' border='0' alt='Μηνάς Παπαθωμάς' title='Μηνάς Παπαθωμάς'  /></a></div>
				<div class="texts">
					<h3><a href="content.asp?id=2060&title=minas-papathomas-" title="Μηνάς Παπαθωμάς">Μηνάς Παπαθωμάς</a></h3>
					
					<p class="social">
						
							<a href="https://www.facebook.com/minas.papathomas" target="_blank" class="facebook">facebook</a>
						
					</p>
				</div>
			</li>
		
			<li>
				<div class="photo"><a href="content.asp?id=2061&title=grigoris-payloy-" title="Γρηγόρης Παύλου"><img src='/datafiles/cms2061.jpg?width=79' border='0' alt='Γρηγόρης Παύλου' title='Γρηγόρης Παύλου'  /></a></div>
				<div class="texts">
					<h3><a href="content.asp?id=2061&title=grigoris-payloy-" title="Γρηγόρης Παύλου">Γρηγόρης Παύλου</a></h3>
					
					<p class="social">
						
							<a href="https://www.facebook.com/gregor.pavlou.7" target="_blank" class="facebook">facebook</a>
						
					</p>
				</div>
			</li>
		
</ul>
				</section>
				
				

				<section class="facebookbox notitle">
					<!--
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0"></script>
<div class="fb-like" data-href="https://www.radiothiva.gr/content/5782/koronoios-eksi-nea-kroysmata-sti-boiotia-deka-stin-eyboia-" data-layout="standard" data-action="like" data-show-faces="true"></div>
-->


<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fradiothiva%2F&tabs=timeline&width=340&height=500&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=false&appId=586856574669799" width="340" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
				</section>			
				
				
				
			</aside>
	  
      
    </div>
</main>

<footer>
	<section class="quotes">
		<div class="box">
			<h2>Η μουσική και ο ρυθμός βρίσκουν το δρόμο τους προς τα πιο απόκρυφα μέρη της ψυχής</h2>
			<p>Πλάτων</p>
		</div>
	</section>
	<div class="box">
		<div class="info">
			<div class="textbox">
				<div class="logo">Radio Thiva</div>
				<p>Το 1989 ο νομός Βοιωτίας αποκτά το δικό του Ελεύθερο Ραδιόφωνο με την ονομασία Ράδιο Θήβα 97,5.</p>
<p>Η εμβέλεια του αλλάζει και σηματοδοτεί το περιφερειακό Ραδιόφωνο της Στερεάς Ελλάδας με κύριο στόχο του την Ενημέρωση.</p>				
			</div>
			<div class="contact"><p class="address">ΑΙΣΩΠΟΥ 7.32200</p>
<p class="phone">T: <a href="tel:2262081273">22620 81273/81283</a></p>
<p class="fax">F: 22620 28117</p>
<p class="email"><a href="mailto:info@radiothiva.gr?subject=Mail from Our Site">info@radiothiva.gr</a></p></div>
		</div>
		<div class="bottom">
			<p>
				
						<a href="content.asp?id=51&title=oroi-xrisis-">ΟΡΟΙ ΧΡΗΣΗΣ</a>&nbsp;|&nbsp;
					
						<a href="content.asp?id=52&title=politiki-prostasias-dedomenon-">ΠΟΛΙΤΙΚΗ ΠΡΟΣΤΑΣΙΑΣ ΔΕΔΟΜΕΝΩΝ</a>&nbsp;|&nbsp;
					
						<a href="content.asp?id=53&title=rss-">RSS</a>&nbsp;|&nbsp;
					
						<a href="content.asp?id=54&title=epikoinonia-">ΕΠΙΚΟΙΝΩΝΙΑ</a>&nbsp;|&nbsp;
					
			© 2019 RADIOTHIVA.GR</p>
			<p>ΚΑΤΑΣΚΕΥΗ ΙΣΤΟΣΕΛΙΔΩΝ <a href="https://www.hellassites.gr/" target="_blank">HELLASSITES</a></p>
			<a href="#" class="backtotop">Scroll to top</a>
		</div>
	</div>
</footer>

</body>
</html>